[project]
name = "raki-matrimony-docs"
version = "0.0.1"
description = "Raki matrimony a part of RakiFoundation"
authors = [
    {name= "Rakesh Nagarajan", email= "rakesh.core01@gmail.com"}
]
readme = "README.md"
requires-python = ">3.12"
dependencies = ["mkdocs-material (>=9.7.3,<10.0.0)", "zensical (>=0.0.24,<0.0.25)"]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"